name:                stacktrace-plugin
version:             0.1.0.0
github:              "githubuser/stacktrace-plugin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stacktrace-plugin#readme>

library:
  source-dirs: src

dependencies:
- base >= 4.7 && < 5
- directory
# - haskell-stack-trace-plugin >= 0.1.3.0

executables:
  stacktrace-plugin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -fplugin=StackTrace.Plugin
    - -threaded
    # - -prof
    - -rtsopts
    - -with-rtsopts=-N
    # dependencies:
    #- stacktrace-plugin

tests:
  stacktrace-plugin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stacktrace-plugin
